// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-active-rentals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_active_rentals_default = defineTool({
  name: "list_active_rentals",
  title: "Listar alquileres activos",
  description: "Devuelve los alquileres actualmente activos (status = 'active') de LavaExpress, con cliente, zona, servicio, repartidor y hora de entrega.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const { data, error } = await db(ctx).from("rentals").select(
      "id, client_name, phone, address, zone, service_type, price, total, delivered_by, entry_time, status"
    ).eq("status", "active").order("entry_time", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rentals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-rentals-by-date.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_rentals_by_date_default = defineTool2({
  name: "list_rentals_by_date",
  title: "Listar alquileres por fecha",
  description: "Devuelve los alquileres creados en una fecha espec\xEDfica (zona horaria America/Bogota). Formato de fecha: YYYY-MM-DD.",
  inputSchema: {
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha en formato YYYY-MM-DD (hora Colombia)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const startUtc = `${date}T05:00:00.000Z`;
    const end = /* @__PURE__ */ new Date(`${date}T05:00:00.000Z`);
    end.setUTCDate(end.getUTCDate() + 1);
    const { data, error } = await db2(ctx).from("rentals").select(
      "id, client_name, zone, service_type, total, status, delivered_by, picked_up_by, entry_time, completed_at, created_at"
    ).gte("created_at", startUtc).lt("created_at", end.toISOString()).order("created_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rentals: data ?? [], date }
    };
  }
});

// src/lib/mcp/tools/get-daily-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_daily_summary_default = defineTool3({
  name: "get_daily_summary",
  title: "Resumen diario de caja",
  description: "Suma ingresos, egresos y balance de los movimientos de caja para una fecha (zona horaria America/Bogota). Formato YYYY-MM-DD.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha en formato YYYY-MM-DD (hora Colombia)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const startUtc = `${date}T05:00:00.000Z`;
    const end = new Date(startUtc);
    end.setUTCDate(end.getUTCDate() + 1);
    const { data, error } = await db3(ctx).from("cash_entries").select("type, amount, description, category, created_at").gte("created_at", startUtc).lt("created_at", end.toISOString());
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const income = rows.filter((r) => r.type === "income").reduce((s, r) => s + Number(r.amount), 0);
    const expense = rows.filter((r) => r.type === "expense").reduce((s, r) => s + Number(r.amount), 0);
    const summary = { date, income, expense, balance: income - expense, count: rows.length };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/search-clients.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_clients_default = defineTool4({
  name: "search_clients",
  title: "Buscar clientes",
  description: "Busca clientes de LavaExpress por nombre, tel\xE9fono o direcci\xF3n (coincidencia parcial, insensible a may\xFAsculas).",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Texto a buscar en nombre, tel\xE9fono o direcci\xF3n"),
    limit: z3.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (por defecto 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const q = query.replace(/[%,]/g, " ");
    const { data, error } = await db4(ctx).from("clients").select("id, name, phone, address, active, created_at").or(`name.ilike.%${q}%,phone.ilike.%${q}%,address.ilike.%${q}%`).eq("active", true).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-delivery-people.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_delivery_people_default = defineTool5({
  name: "list_delivery_people",
  title: "Listar personal de reparto",
  description: "Devuelve el personal de reparto activo de LavaExpress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const { data, error } = await db5(ctx).from("delivery_people").select("id, name, phone, active").eq("active", true).order("name");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { delivery_people: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hzouqdvqxcnynslaetfr";
var mcp_default = defineMcp({
  name: "lavaexpress-mcp",
  title: "LavaExpress MCP",
  version: "0.1.0",
  instructions: "Herramientas para consultar datos operativos de LavaExpress (alquileres activos y por fecha, resumen de caja, clientes y personal de reparto). Todas las herramientas leen datos como el usuario autenticado y respetan RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_active_rentals_default,
    list_rentals_by_date_default,
    get_daily_summary_default,
    search_clients_default,
    list_delivery_people_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
